# Generated by Django 4.1.7 on 2023-05-16 12:25

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sname',
            field=models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(10), app.models.not_s_A]),
        ),
    ]
